import Head from 'next/head';
import styles from '../styles/Home.module.css'
import cx from 'classnames';
import useSWR from 'swr';
import path from 'path';


const fetcher = (url) => fetch(url).then((res) => res.json());

function dashboard() {
    const { data, error } = useSWR('/api/staticdata', fetcher);
    return (
        <div className={styles.container}>
            <Head>
                <title>TARP-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={cx(styles["form-signin"], "text-center", "mt-5", "main")}>

                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        if (error)
                            console.log(error);
                        if (!error && !data)
                            console.log("Loading...");
                        if (data) {
                            // window.open(path.join(process.cwd(), 'public') + "/data.json", "_blank");
                            window.open("http://localhost:3000/data.json", "_blank");
                        }
                    }}
                >
                    <h1 className="h3 mb-3 fw-normal text-light">Dashboard</h1>

                    <div className="form-floating mb-3">
                        <textarea type="text" className="form-control" id="Input" placeholder="Enter Text" />
                        <label htmlFor="Input">Enter Text</label>
                    </div>
                    <button className="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    )
}

export default dashboard